api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    directory: /etc/traefik/dynamic
    watch: false

http:
  middlewares:
    https-redirect:
      redirectscheme:
        scheme: https
        permanent: true

certificatesResolvers:
  cert-1:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: admin@tsb.one
      storage: /letsencrypt/acme-1.json
      dnsChallenge:
        provider: 'googledomains'
        delayBeforeCheck: 20
        resolvers:
          - 8.8.8.8
          - 8.8.4.4