version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./letsencrypt.${HOSTNAME}:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./opt:/etc/traefik:ro"
    restart: always
    env_file: .env
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      - "traefik.http.routers.to-dashboard.entrypoints=https"
#      - "traefik.http.routers.to-dashboard.tls=true"
#      - "traefik.http.routers.to-dashboard.rule=Host(`${HOSTNAME_FQDN}`) && PathPrefix(`/api`, `/dashboard`)"
#      - "traefik.http.routers.to-dashboard.service=api@internal"

networks:
  proxy:
    external: true
