version: "3.3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - proxy
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nginx-https.entrypoints=https"
      - "traefik.http.routers.nginx-https.rule=Host(`${NGINX_HOSTNAME}`)"
      - "traefik.http.routers.nginx-https.tls=true"
      - "traefik.http.routers.nginx-https.tls.certresolver=cert-1"
      - "traefik.http.routers.nginx-https.service=nginx-loadbal"
      - "traefik.http.services.nginx-loadbal.loadbalancer.server.port=8081"

networks:
  proxy:
    external: true
